services:
    _defaults:
        autowire: true
        autoconfigure: true

    Dneustadt\CsrfCookieBundle\EventSubscriber\KernelEventSubscriber:
        arguments:
            $cookieName: '%dneustadt_csrf_cookie.name%'
            $cookieExpire: '%dneustadt_csrf_cookie.expire%'
            $cookiePath: '%dneustadt_csrf_cookie.path%'
            $cookieDomain: '%dneustadt_csrf_cookie.domain%'
            $cookieSecure: '%dneustadt_csrf_cookie.secure%'
        tags:
            - { name: 'event_subscriber' }
